### PR TITLE
updated patch for nginx 1.25.3

### PR DESCRIPTION
**Pull request by eilandert**

### CODE REVIEW

**Comment by Dead2** [comment]
@eilandert I forgot to ask, did you test this updated patch to make sure there were no warnings in the nginx logs?

**Comment by eilandert** [comment]
> @eilandert I forgot to ask, did you test this updated patch to make sure there were no warnings in the nginx logs?

I run it on production on a couple of servers, never seen any warning so far.

**Comment by Dead2** [comment]
@eilandert To be clear, the updated patch and not the original patch, right?
I remember you saying you had the original patch running on servers, so just want to make sure. 😄

**Comment by eilandert** [comment]
> @eilandert To be clear, the updated patch and not the original patch, right? I remember you saying you had the original patch running on servers, so just want to make sure. 😄

lol yes, I apply this exact patch on each update now.

**Comment by Dead2** [comment]
Thanks 😃

**Pull request merged**
